export const postList = [
    {
      id:'S4Nj2NJusTNlnQFibREI',
      caption:'Blå Dress XS H&M',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684202738/ticktock/Video/blue_dress_t9gtdg.mov',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'Blå Dress XS H&M',
      topic:'Blå Dress XS H&M',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'599 kr',
      description:'Köp nu',
      productName:'Blå Dress XS H&M',
      isAvailable:false,
    },
    {
      id:'v7lQczJiRA5zthk8rAUz',
      caption:'Glitterkjol S H&M',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684202745/ticktock/Video/puder_glitterkjol_sa3gwp.mov',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243226/cld-sample-4.jpg',
      songName:'Glitterkjol S H&M',
      topic:'Glitterkjol S H&M',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'499 kr',
      description:'Glitterkjol S H&M',
      productName:'Glitterkjol S H&M',
      isAvailable:false,
    },
    {
      id:'oDOkd4hCm8rogMGuz0oX',
      caption:'Vitt dress från Acne',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684202743/ticktock/Video/vitt_s6afdz.mov',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243226/cld-sample-4.jpg',
      songName:'Vitt dress från Acne',
      topic:'Vitt dress från Acne',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'799 kr',
      description:'Vitt dress från Acne',
      productName:'Vitt dress från Acne',
      isAvailable:true,
    },
    {
      id:'Knzbrmbj5U5bMml3NT1g',
      caption:'Olika kläder',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684205286/store/IMG_9607_il6iv0.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'Olika kläder',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'599 kr',
      description:'Olika kläder',
      productName:'Olika kläder',
      isAvailable: true,
    },
   {
      id:'Ky2IylFti9i17aECgoc3L',
      caption:'Soft Goat S ',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684204080/Community%20content/SoftGoat_cxrugw.mov',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'Soft Goat S ',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'699 kr',
      description:'Soft Goat S ',
      productName:'Soft Goat S ',
      isAvailable:true,
    },
    {
      id:'ivm1NUZaS06ZXoGCiT2gl',
      caption:'Jacka S',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684204077/Community%20content/Gold2_rdamue.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'Jacka S',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'699 kr',
      description:'Jacka S',
      productName:'Jacka S',
      isAvailable:false,
    },
  {
    id:'GcaAwLzKUkwWRgZIy5JG121',
    caption:'test-test',
    company:'nileshdev0707@gmail.com',
    image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684202735/ticktock/MulitContent/41_oiamz6.mov',
    profileImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1684202729/ticktock/MulitContent/41_yemn8e.webp',
    productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
    songName:'',
    topic:'development',
    userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
    username:'nilesh dev',
    price:'599 kr',
    description:'Kavaj från COS S',
    productName:'Kavaj från COS S',
    isAvailable:false,
  },
  {
    id:'GcaAwLzKUkwWRgZIy5JG0',
    caption:'T-Shirt från Down XS',
    company:'nileshdev0707@gmail.com',
    image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684202735/ticktock/MulitContent/41_oiamz6.mov',
    profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
    productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1684202729/ticktock/MulitContent/2_yfjfyc.webp',
    songName:'',
    topic:'development',
    userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
    username:'nilesh dev',
    price:'1099 kr',
    description:'T-Shirt från Down XS',
    productName:'T-Shirt från Down XS',
    isAvailable:false,
  },
  {
    id:'GcaAwLzKUkwWRgZIy5JG2',
    caption:'T-Shirt från Down XS',
    company:'nileshdev0707@gmail.com',
    image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684202735/ticktock/MulitContent/41_oiamz6.mov',
    profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
    productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1684202728/ticktock/MulitContent/24_swdfpu.webp',
    songName:'',
    topic:'development',
    userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
    username:'nilesh dev',
    price:'499 kr',
    description:'Klänning från COS S',
    productName:'Klänning från COS S',
    isAvailable:false,
  },
  {
    id:'GcaAwLzKUkwWRgZIy5JG1',
    caption:'Kjol från Acne M',
    company:'nileshdev0707@gmail.com',
    image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1684202735/ticktock/MulitContent/41_oiamz6.mov',
    profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
    productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1684202728/ticktock/MulitContent/35_vb7w8j.webp',
    songName:'',
    topic:'development',
    userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
    username:'nilesh dev',
    price:'499 kr',
    description:'Kjol från Acne M',
    productName:'Kjol från Acne M',
    isAvailable:false,
  }
]