export const postList = [
    {
      id:'S4Nj2NJusTNlnQFibREI',
      caption:'dance',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1681792667/One_of_the_best_dunks_in_2022_fy_fyp_shoes_jordan4_travisscott_dunklow_nike_resell_cheap_dunk_jordan_7184773882862144773_1_v5i8u1.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'dance!MUV',
      topic:'food',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'200$',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      productName:'shoes',
      isAvailable:false,
    },
    {
      id:'v7lQczJiRA5zthk8rAUz',
      caption:'sampla this is free',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1680243218/samples/sea-turtle.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243226/cld-sample-4.jpg',
      songName:'asindl sdsid',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'1200$',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      productName:'Nike shoes',
      isAvailable:false,
    },
    {
      id:'oDOkd4hCm8rogMGuz0oX',
      caption:'sampla this is free',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1680243222/samples/cld-sample-video.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243226/cld-sample-4.jpg',
      songName:'nil ad sdjakjs asas',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'400$',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      productName:'Bata shoes',
      isAvailable:true,
    },
    {
      id:'Knzbrmbj5U5bMml3NT1g',
      caption:'test-test',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1680243259/SampleVideo_1280x720_2mb_ylv00z.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'test-test',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'910$',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      productName:'Mens shoes',
      isAvailable:false,
    },
    {
      id:'GcaAwLzKUkwWRgZIy5JG',
      caption:'test-test',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1680243222/samples/cld-sample-video.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'asindl sdsid',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'2600$',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      productName:'canvas shoes',
      isAvailable:false,
    }, {
      id:'ivm1NUZaS06ZXoGCiTgl',
      caption:'dasd adsa',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1680243220/samples/elephants.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'sdsa adsalaslo22 2osdsd sdsds',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'20$',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      productName:'sports shoes',
      isAvailable:false,
    }, {
      id:'Ky2IylFti9i7aECgoc3L',
      caption:'test-test',
      company:'nileshdev0707@gmail.com',
      image:'https://res.cloudinary.com/drqknzm5v/video/upload/v1680243218/samples/sea-turtle.mp4',
      profileImage:'https://lh5.googleusercontent.com/-nvsAZ5Vtafk/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckaxCXawWng-jEZY66mABkr36cB1Q/s96-c/photo.jpg',
      productImage:'https://res.cloudinary.com/drqknzm5v/image/upload/v1680243227/cld-sample-5.jpg',
      songName:'test',
      topic:'development',
      userId:'WmEoLWOsxmTFjDipMxCMxW7ft5f1',
      username:'nilesh dev',
      price:'770$',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      productName:'Runner-up shoes',
      isAvailable:true,
    }
]